dist: trusty

 before_install:
  - sudo apt-get -y install libxml2-dev libu2f-udev libvulkan1

language: node_js
 node_js:
   - "stable"

 addons:
   apt:
     update: true
     sources:
       - google-chrome
     packages:
       - google-chrome-stable

 cache:
   directories:
      - ./node_modules

 install:
   - yarn install

 script:
   - yarn run test
   - yarn run build
